# Generated by Django 4.2.2 on 2023-06-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('symbol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.IntegerField(blank=True, default=60, null=True, verbose_name='Monitoramento em minutos')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ativo')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.email')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ativo')),
            ],
        ),
    ]
