# Generated by Django 4.2.2 on 2023-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_ativo_active_monitoramento_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoramento",
            name="last_view",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoramento",
            name="next_view",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
