name: Django CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Instalar dependências
      run: |
        pip install -r requirements.txt
    - name: Formatação com Black
      run: |
        black .
    - name: Copiar env
      run: |
        cp .env-sample .env
    - name: Rodando os Pytest
      run: |
        pytest
